name: linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint check
        uses: azohra/shell-linter@v0.3.0
        env:
          SHELLCHECK_OPTS: "-e SC1008 -e SC1071"
